<?php

class ale_global {
    //generate unique_ids
    private static $ale_unique_counter = 0;

    static function ale_generate_unique_id() {
        self::$ale_unique_counter++;
        return 'ale_uid_' . self::$ale_unique_counter . '_' . uniqid();
    }

    // Demo and plugins list
    public static $demo_list = array();

    public static $plugins_list = array();

    static $ale_options;

}

//Demos Base
ale_global::$demo_list = array(
    'pizza'       => array(
        'text'             => 'Pizza',
        'folder'           => get_template_directory() . '/aletheme/demos/pizza/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=46',
        'category'         => array(
            'all',
            'micro-niche',
            'shop',
            'free'
        ),
        'date-create'      => '2024-05-20',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/pizza.png',
        'required_plugins' => array('cpt-aletheme', 'woocommerce'),
        'builder'          => array('elementor'),
        'info'             => '',
        'premium'          => false,
    ),
    'mimi'        => array(
        'text'             => 'Mimi Kids',
        'folder'           => get_template_directory() . '/aletheme/demos/mimi/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=45',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2024-05-15',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/alekids.jpg',
        'required_plugins' => array('cpt-aletheme', 'woocommerce'),
        'builder'          => array('elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'cosushi'     => array(
        'text'             => 'coSushi',
        'folder'           => get_template_directory() . '/aletheme/demos/cosushi/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=2',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-11-15',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/cosushi.jpg',
        'required_plugins' => array(
            'cpt-aletheme',
            'revslider',
            'woocommerce',
            'contact-form-7'
        ),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'delizioso'   => array(
        'text'             => 'Delizioso',
        'folder'           => get_template_directory() . '/aletheme/demos/delizioso/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=4',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-10-04',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/delizioso.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'woocommerce'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'moka'        => array(
        'text'             => 'Moka',
        'folder'           => get_template_directory() . '/aletheme/demos/moka/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=1',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-09-20',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/moka.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'woocommerce'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'kitty'       => array(
        'text'             => 'Kitty',
        'folder'           => get_template_directory() . '/aletheme/demos/kitty/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=8',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-09-07',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/kitty.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'woocommerce'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'laptica'     => array(
        'text'             => 'Laptica',
        'folder'           => get_template_directory() . '/aletheme/demos/laptica/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=13',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-08-31',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/laptica.jpg',
        'required_plugins' => array(
            'cpt-aletheme',
            'revslider',
            'woocommerce',
            'ti-woocommerce-wishlist'
        ),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'burger'      => array(
        'text'             => 'Burger',
        'folder'           => get_template_directory() . '/aletheme/demos/burger/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=3',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2020-08-20',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/burger.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'woocommerce'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'bebe'        => array(
        'text'             => 'Bebe',
        'folder'           => get_template_directory() . '/aletheme/demos/bebe/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=6',
        'category'         => array('all', 'micro-niche', 'creative'),
        'date-create'      => '2021-08-09',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/bebe.jpg',
        'required_plugins' => array('cpt-aletheme', 'regenerate-thumbnails'),
        'builder'          => array('js_composer'),
        'info'             => '<i class="fa fa-info-circle"></i> ' . esc_html__( 'After Import finished, you should regenerate thumbnails: Tools', 'ale' ) . ' -> <a href="' . admin_url( "/" ) . 'tools.php?page=regenerate-thumbnails#/">Regenerate Thumbnails</a>',
        'premium'          => true,
    ),
    'po'          => array(
        'text'             => 'Po',
        'folder'           => get_template_directory() . '/aletheme/demos/po/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=21',
        'category'         => array(
            'all',
            'micro-niche',
            'photography',
            'free'
        ),
        'date-create'      => '2020-01-06',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/po.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => false,
    ),
    'smoothie'    => array(
        'text'             => 'Smoothie',
        'folder'           => get_template_directory() . '/aletheme/demos/smoothie/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=12',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-12-22',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/smoothie.jpg',
        'required_plugins' => array(
            'cpt-aletheme',
            'woocommerce',
            'revslider',
            'mailchimp-for-wp'
        ),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'hai'         => array(
        'text'             => 'Hai',
        'folder'           => get_template_directory() . '/aletheme/demos/hai/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=11',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-12-6',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/hai.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'mailchimp-for-wp'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'organic'     => array(
        'text'             => 'Organic',
        'folder'           => get_template_directory() . '/aletheme/demos/organic/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=10',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-11-27',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/organic.jpg',
        'required_plugins' => array('cpt-aletheme', 'woocommerce', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'cafeteria'   => array(
        'text'             => 'Cafeteria',
        'folder'           => get_template_directory() . '/aletheme/demos/cafeteria/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=29',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-11-20',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/cafeteria.jpg',
        'required_plugins' => array('cpt-aletheme', 'woocommerce', 'cpt-editor'),
        'builder'          => array('js_composer', 'elementor'),
        'info'             => '',
        'premium'          => true,
    ),
    'nunta'       => array(
        'text'             => 'Nunta',
        'folder'           => get_template_directory() . '/aletheme/demos/nunta/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=23',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-11-16',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/nunta.jpg',
        'required_plugins' => array('cpt-aletheme', 'cpt-editor'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'limpieza'    => array(
        'text'             => 'Limpieza',
        'folder'           => get_template_directory() . '/aletheme/demos/limpieza/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=44',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-11-12',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/limpieza.jpg',
        'required_plugins' => array('cpt-aletheme', 'contact-form-7', 'cpt-editor'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'orquidea'    => array(
        'text'             => 'Orquidea',
        'folder'           => get_template_directory() . '/aletheme/demos/orquidea/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=26',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-10-29',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/orquidea.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'donation'    => array(
        'text'             => 'Donation',
        'folder'           => get_template_directory() . '/aletheme/demos/donation/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=36',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-10-25',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/donation.jpg',
        'required_plugins' => array('cpt-aletheme', 'mailchimp-for-wp', 'seamless-donations'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'enforcement' => array(
        'text'             => 'Enforcement',
        'folder'           => get_template_directory() . '/aletheme/demos/enforcement/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=24',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-10-12',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/enforcement.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'ospedale'    => array(
        'text'             => 'Ospedale',
        'folder'           => get_template_directory() . '/aletheme/demos/ospedale/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=22',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-10-5',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/ospedale.jpg',
        'required_plugins' => array('cpt-aletheme', 'mailchimp-for-wp', 'contact-form-7'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'prestigio'   => array(
        'text'             => 'Prestigio',
        'folder'           => get_template_directory() . '/aletheme/demos/prestigio/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=38',
        'category'         => array(
            'all',
            'business',
            'creative',
            'one-page'
        ),
        'date-create'      => '2019-05-2',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/prestigio.jpg',
        'required_plugins' => array('cpt-aletheme', 'mailchimp-for-wp', 'page-scroll-to-id'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'taxipress'   => array(
        'text'             => 'TaxiPress',
        'folder'           => get_template_directory() . '/aletheme/demos/taxipress/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=20',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-05-1',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/taxipress.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'exotico'     => array(
        'text'             => 'Exotico',
        'folder'           => get_template_directory() . '/aletheme/demos/exotico/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=15',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-04-1',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/exotico.jpg',
        'required_plugins' => array('woocommerce', 'cpt-aletheme', 'mailchimp-for-wp'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'keira'       => array(
        'text'             => 'Keira',
        'folder'           => get_template_directory() . '/aletheme/demos/keira/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=7',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-03-1',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/keira.jpg',
        'required_plugins' => array('woocommerce', 'cpt-aletheme', 'mailchimp-for-wp'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'rosi'        => array(
        'text'             => 'Rosi',
        'folder'           => get_template_directory() . '/aletheme/demos/rosi/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=5',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-01-1',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/rosi.jpg',
        'required_plugins' => array(
            'woocommerce',
            'cpt-aletheme',
            'mailchimp-for-wp',
            'revslider',
            'ti-woocommerce-wishlist'
        ),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'blackwhite'  => array(
        'text'             => 'Olins',
        'folder'           => get_template_directory() . '/aletheme/demos/blackwhite/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=35',
        'category'         => array('all', 'creative', 'shop'),
        'date-create'      => '2019-01-1',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/bw.jpg',
        'required_plugins' => array('woocommerce', 'cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'zoo'         => array(
        'text'             => 'Zoo',
        'folder'           => get_template_directory() . '/aletheme/demos/zoo/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=43',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-01-2',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/zoo.jpg',
        'required_plugins' => array(
            'cpt-aletheme',
            'cpt-editor',
            'mailchimp-for-wp',
            'revslider'
        ),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'bakery'      => array(
        'text'             => 'Bakery',
        'folder'           => get_template_directory() . '/aletheme/demos/bakery/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=41',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-01-3',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/bakery.jpg',
        'required_plugins' => array('woocommerce', 'cpt-aletheme', 'mailchimp-for-wp'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'photography' => array(
        'text'             => 'Photography',
        'folder'           => get_template_directory() . '/aletheme/demos/photography/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=40',
        'category'         => array('all', 'photography'),
        'date-create'      => '2019-01-4',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/photography.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'luxuryshoes' => array(
        'text'             => 'LuxuryShoes',
        'folder'           => get_template_directory() . '/aletheme/demos/luxuryshoes/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=31',
        'category'         => array('all', 'micro-niche', 'shop'),
        'date-create'      => '2019-01-5',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/luxuryshoes.jpg',
        'required_plugins' => array('cpt-aletheme', 'woocommerce'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'camping'     => array(
        'text'             => 'Camping',
        'folder'           => get_template_directory() . '/aletheme/demos/camping/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=16',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-01-6',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/camping.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'travelphoto' => array(
        'text'             => 'TravelPhotography',
        'folder'           => get_template_directory() . '/aletheme/demos/travelphoto/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=30',
        'category'         => array('all', 'photography'),
        'date-create'      => '2019-01-7',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/travelphoto.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'viaje'       => array(
        'text'             => 'Viaje',
        'folder'           => get_template_directory() . '/aletheme/demos/viaje/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=9',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-01-8',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/viaje.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'wedding'     => array(
        'text'             => 'Wedding',
        'folder'           => get_template_directory() . '/aletheme/demos/wedding/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=25',
        'category'         => array('all', 'photography', 'micro-niche'),
        'date-create'      => '2019-01-9',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/wedding.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'furniture'   => array(
        'text'             => 'Furniture',
        'folder'           => get_template_directory() . '/aletheme/demos/furniture/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=42',
        'category'         => array('all', 'micro-niche'),
        'date-create'      => '2019-01-10',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/furniture.jpg',
        'required_plugins' => array('cpt-aletheme', 'cpt-editor', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'magazine'    => array(
        'text'             => 'Magazine',
        'folder'           => get_template_directory() . '/aletheme/demos/magazine/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=39',
        'category'         => array('all', 'creative'),
        'date-create'      => '2019-01-11',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/magazine.jpg',
        'required_plugins' => array('cpt-aletheme', 'mailchimp-for-wp'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'creative'    => array(
        'text'             => 'Creative',
        'folder'           => get_template_directory() . '/aletheme/demos/creative/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=17',
        'category'         => array('all', 'creative'),
        'date-create'      => '2019-03-29',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/creative.jpg',
        'required_plugins' => array('cpt-aletheme', 'cpt-editor', 'revslider'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'brigitte'    => array(
        'text'             => 'Brigitte',
        'folder'           => get_template_directory() . '/aletheme/demos/brigitte/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=14',
        'category'         => array('all', 'photography'),
        'date-create'      => '2019-04-01',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/brigitte.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'corporate'   => array(
        'text'             => 'Corporate',
        'folder'           => get_template_directory() . '/aletheme/demos/corporate/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=37',
        'category'         => array('all', 'business', 'one-page'),
        'date-create'      => '2019-04-03',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/corporate.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'page-scroll-to-id'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'cv'          => array(
        'text'             => 'CV',
        'folder'           => get_template_directory() . '/aletheme/demos/cv/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=32',
        'category'         => array(
            'all',
            'business',
            'creative',
            'one-page'
        ),
        'date-create'      => '2019-04-06',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/cv.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'page-scroll-to-id'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'fashion'     => array(
        'text'             => 'Fashion',
        'folder'           => get_template_directory() . '/aletheme/demos/fashion/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=18',
        'category'         => array('all', 'shop'),
        'date-create'      => '2019-04-10',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/fashion.jpg',
        'required_plugins' => array('cpt-aletheme', 'revslider', 'woocommerce'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'pastel'      => array(
        'text'             => 'Pastel',
        'folder'           => get_template_directory() . '/aletheme/demos/pastel/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=33',
        'category'         => array('all', 'creative', 'photography'),
        'date-create'      => '2019-04-13',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/pastel.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'stephanie'   => array(
        'text'             => 'Stephanie',
        'folder'           => get_template_directory() . '/aletheme/demos/stephanie/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=19',
        'category'         => array('all', 'photography'),
        'date-create'      => '2019-04-18',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/stephanie.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'cameron'     => array(
        'text'             => 'Cameron',
        'folder'           => get_template_directory() . '/aletheme/demos/cameron/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=27',
        'category'         => array('all', 'photography', 'creative'),
        'date-create'      => '2019-04-24',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/cameron.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'pixel'       => array(
        'text'             => 'Pixel',
        'folder'           => get_template_directory() . '/aletheme/demos/pixel/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=28',
        'category'         => array('all', 'creative'),
        'date-create'      => '2019-04-25',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/pixel.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
    'jade'        => array(
        'text'             => 'Jade',
        'folder'           => get_template_directory() . '/aletheme/demos/jade/',
        'demo_url'         => 'https://aletheme.com/demos/?demo=34',
        'category'         => array('all', 'creative', 'photography'),
        'date-create'      => '2019-05-04',
        'demo_preview'     => ALETHEME_DEMOS_HOST . 'olins_base/preview_screen/jade.jpg',
        'required_plugins' => array('cpt-aletheme'),
        'builder'          => array('js_composer'),
        'info'             => '',
        'premium'          => true,
    ),
);
//Plugins Base
$ale_premium_plugins = array();
$ale_free_plugins = array(
    'elementor'               => array(
        'name'     => 'Elementor Website Builder',
        'location' => 'wp_repo',
        'slug'     => 'elementor',
    ),
    'woocommerce'             => array(
        'name'     => 'WooCommerce',
        'location' => 'wp_repo',
        'slug'     => 'woocommerce',
    ),
    'regenerate-thumbnails'   => array(
        'name'     => 'Regenerate Thumbnails',
        'location' => 'wp_repo',
        'slug'     => 'regenerate-thumbnails',
    ),
    'ti-woocommerce-wishlist' => array(
        'name'     => 'WooCommerce Wishlist Plugin',
        'location' => 'wp_repo',
        'slug'     => 'ti-woocommerce-wishlist',
    ),
    'page-scroll-to-id'       => array(
        'name'     => 'Page scroll to id',
        'location' => 'wp_repo',
        'slug'     => 'page-scroll-to-id',
    ),
    'cpt-editor'              => array(
        'name'     => 'Custom Post Type Editor',
        'location' => 'wp_repo',
        'slug'     => 'cpt-editor',
    ),
    'mailchimp-for-wp'        => array(
        'name'     => 'MailChimp for WordPress',
        'location' => 'wp_repo',
        'slug'     => 'mailchimp-for-wp',
    ),
    'contact-form-7'          => array(
        'name'     => 'Contact Form 7',
        'location' => 'wp_repo',
        'slug'     => 'contact-form-7',
    ),
    'seamless-donations'      => array(
        'name'     => 'Seamless Donations',
        'location' => 'wp_repo',
        'slug'     => 'seamless-donations',
    ),
    'cpt-aletheme'            => array(
        'name'     => 'Ale Core',
        'location' => 'bundled',
        'slug'     => 'cpt-aletheme',
        'source'   => ALETHEME_THEME_URL . '/plugins/cpt-aletheme.zip',
    ),
);
ale_global::$plugins_list = array_merge( $ale_free_plugins, $ale_premium_plugins );